// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sxcustomer.proto

package sxcustomer

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestHeader struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestHeader) Reset()         { *m = RequestHeader{} }
func (m *RequestHeader) String() string { return proto.CompactTextString(m) }
func (*RequestHeader) ProtoMessage()    {}
func (*RequestHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdfd9498686a1cf0, []int{0}
}

func (m *RequestHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestHeader.Unmarshal(m, b)
}
func (m *RequestHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestHeader.Marshal(b, m, deterministic)
}
func (m *RequestHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestHeader.Merge(m, src)
}
func (m *RequestHeader) XXX_Size() int {
	return xxx_messageInfo_RequestHeader.Size(m)
}
func (m *RequestHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestHeader.DiscardUnknown(m)
}

var xxx_messageInfo_RequestHeader proto.InternalMessageInfo

func (m *RequestHeader) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type Employee struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	MiddleName           string   `protobuf:"bytes,2,opt,name=middleName,proto3" json:"middleName,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Position             string   `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	ContactPhone         string   `protobuf:"bytes,5,opt,name=contactPhone,proto3" json:"contactPhone,omitempty"`
	ContactMobile        string   `protobuf:"bytes,6,opt,name=contactMobile,proto3" json:"contactMobile,omitempty"`
	ContactEmail         string   `protobuf:"bytes,7,opt,name=contactEmail,proto3" json:"contactEmail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Employee) Reset()         { *m = Employee{} }
func (m *Employee) String() string { return proto.CompactTextString(m) }
func (*Employee) ProtoMessage()    {}
func (*Employee) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdfd9498686a1cf0, []int{1}
}

func (m *Employee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Employee.Unmarshal(m, b)
}
func (m *Employee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Employee.Marshal(b, m, deterministic)
}
func (m *Employee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Employee.Merge(m, src)
}
func (m *Employee) XXX_Size() int {
	return xxx_messageInfo_Employee.Size(m)
}
func (m *Employee) XXX_DiscardUnknown() {
	xxx_messageInfo_Employee.DiscardUnknown(m)
}

var xxx_messageInfo_Employee proto.InternalMessageInfo

func (m *Employee) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Employee) GetMiddleName() string {
	if m != nil {
		return m.MiddleName
	}
	return ""
}

func (m *Employee) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Employee) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

func (m *Employee) GetContactPhone() string {
	if m != nil {
		return m.ContactPhone
	}
	return ""
}

func (m *Employee) GetContactMobile() string {
	if m != nil {
		return m.ContactMobile
	}
	return ""
}

func (m *Employee) GetContactEmail() string {
	if m != nil {
		return m.ContactEmail
	}
	return ""
}

type RequestField struct {
	CustomerType         string      `protobuf:"bytes,1,opt,name=customerType,proto3" json:"customerType,omitempty"`
	Prefix               string      `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	FirstName            string      `protobuf:"bytes,3,opt,name=firstName,proto3" json:"firstName,omitempty"`
	MiddleName           string      `protobuf:"bytes,4,opt,name=middleName,proto3" json:"middleName,omitempty"`
	LastName             string      `protobuf:"bytes,5,opt,name=lastName,proto3" json:"lastName,omitempty"`
	OrganisationName     string      `protobuf:"bytes,6,opt,name=organisationName,proto3" json:"organisationName,omitempty"`
	ContactEmail         string      `protobuf:"bytes,7,opt,name=contactEmail,proto3" json:"contactEmail,omitempty"`
	ContactMobile        string      `protobuf:"bytes,8,opt,name=contactMobile,proto3" json:"contactMobile,omitempty"`
	ContactPhone         string      `protobuf:"bytes,9,opt,name=contactPhone,proto3" json:"contactPhone,omitempty"`
	AddressStreet        string      `protobuf:"bytes,10,opt,name=addressStreet,proto3" json:"addressStreet,omitempty"`
	AddressCity          string      `protobuf:"bytes,11,opt,name=addressCity,proto3" json:"addressCity,omitempty"`
	AddressPostCode      string      `protobuf:"bytes,12,opt,name=addressPostCode,proto3" json:"addressPostCode,omitempty"`
	AddressState         string      `protobuf:"bytes,13,opt,name=addressState,proto3" json:"addressState,omitempty"`
	AddressCountry       string      `protobuf:"bytes,14,opt,name=addressCountry,proto3" json:"addressCountry,omitempty"`
	EmployeeDetails      []*Employee `protobuf:"bytes,15,rep,name=employeeDetails,proto3" json:"employeeDetails,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RequestField) Reset()         { *m = RequestField{} }
func (m *RequestField) String() string { return proto.CompactTextString(m) }
func (*RequestField) ProtoMessage()    {}
func (*RequestField) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdfd9498686a1cf0, []int{2}
}

func (m *RequestField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestField.Unmarshal(m, b)
}
func (m *RequestField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestField.Marshal(b, m, deterministic)
}
func (m *RequestField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestField.Merge(m, src)
}
func (m *RequestField) XXX_Size() int {
	return xxx_messageInfo_RequestField.Size(m)
}
func (m *RequestField) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestField.DiscardUnknown(m)
}

var xxx_messageInfo_RequestField proto.InternalMessageInfo

func (m *RequestField) GetCustomerType() string {
	if m != nil {
		return m.CustomerType
	}
	return ""
}

func (m *RequestField) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *RequestField) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *RequestField) GetMiddleName() string {
	if m != nil {
		return m.MiddleName
	}
	return ""
}

func (m *RequestField) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *RequestField) GetOrganisationName() string {
	if m != nil {
		return m.OrganisationName
	}
	return ""
}

func (m *RequestField) GetContactEmail() string {
	if m != nil {
		return m.ContactEmail
	}
	return ""
}

func (m *RequestField) GetContactMobile() string {
	if m != nil {
		return m.ContactMobile
	}
	return ""
}

func (m *RequestField) GetContactPhone() string {
	if m != nil {
		return m.ContactPhone
	}
	return ""
}

func (m *RequestField) GetAddressStreet() string {
	if m != nil {
		return m.AddressStreet
	}
	return ""
}

func (m *RequestField) GetAddressCity() string {
	if m != nil {
		return m.AddressCity
	}
	return ""
}

func (m *RequestField) GetAddressPostCode() string {
	if m != nil {
		return m.AddressPostCode
	}
	return ""
}

func (m *RequestField) GetAddressState() string {
	if m != nil {
		return m.AddressState
	}
	return ""
}

func (m *RequestField) GetAddressCountry() string {
	if m != nil {
		return m.AddressCountry
	}
	return ""
}

func (m *RequestField) GetEmployeeDetails() []*Employee {
	if m != nil {
		return m.EmployeeDetails
	}
	return nil
}

type RawRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RawRequest) Reset()         { *m = RawRequest{} }
func (m *RawRequest) String() string { return proto.CompactTextString(m) }
func (*RawRequest) ProtoMessage()    {}
func (*RawRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdfd9498686a1cf0, []int{3}
}

func (m *RawRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawRequest.Unmarshal(m, b)
}
func (m *RawRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawRequest.Marshal(b, m, deterministic)
}
func (m *RawRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawRequest.Merge(m, src)
}
func (m *RawRequest) XXX_Size() int {
	return xxx_messageInfo_RawRequest.Size(m)
}
func (m *RawRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RawRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RawRequest proto.InternalMessageInfo

func (m *RawRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type GetRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Id                   int32          `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdfd9498686a1cf0, []int{4}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type CreateRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Field                *RequestField  `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdfd9498686a1cf0, []int{5}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *CreateRequest) GetField() *RequestField {
	if m != nil {
		return m.Field
	}
	return nil
}

type ActionRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Id                   int32          `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string         `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ActionRequest) Reset()         { *m = ActionRequest{} }
func (m *ActionRequest) String() string { return proto.CompactTextString(m) }
func (*ActionRequest) ProtoMessage()    {}
func (*ActionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdfd9498686a1cf0, []int{6}
}

func (m *ActionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionRequest.Unmarshal(m, b)
}
func (m *ActionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionRequest.Marshal(b, m, deterministic)
}
func (m *ActionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionRequest.Merge(m, src)
}
func (m *ActionRequest) XXX_Size() int {
	return xxx_messageInfo_ActionRequest.Size(m)
}
func (m *ActionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ActionRequest proto.InternalMessageInfo

func (m *ActionRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ActionRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ActionRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UpdateRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Id                   int32          `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Field                *RequestField  `protobuf:"bytes,3,opt,name=field,proto3" json:"field,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdfd9498686a1cf0, []int{7}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *UpdateRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateRequest) GetField() *RequestField {
	if m != nil {
		return m.Field
	}
	return nil
}

type DataResponse struct {
	StatusCode           int32              `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message              string             `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *DataResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *DataResponse) Reset()         { *m = DataResponse{} }
func (m *DataResponse) String() string { return proto.CompactTextString(m) }
func (*DataResponse) ProtoMessage()    {}
func (*DataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdfd9498686a1cf0, []int{8}
}

func (m *DataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataResponse.Unmarshal(m, b)
}
func (m *DataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataResponse.Marshal(b, m, deterministic)
}
func (m *DataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataResponse.Merge(m, src)
}
func (m *DataResponse) XXX_Size() int {
	return xxx_messageInfo_DataResponse.Size(m)
}
func (m *DataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DataResponse proto.InternalMessageInfo

func (m *DataResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *DataResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *DataResponse) GetData() *DataResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type DataResponse_Data struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerType         string      `protobuf:"bytes,2,opt,name=customerType,proto3" json:"customerType,omitempty"`
	Prefix               string      `protobuf:"bytes,3,opt,name=prefix,proto3" json:"prefix,omitempty"`
	FirstName            string      `protobuf:"bytes,4,opt,name=firstName,proto3" json:"firstName,omitempty"`
	MiddleName           string      `protobuf:"bytes,5,opt,name=middleName,proto3" json:"middleName,omitempty"`
	LastName             string      `protobuf:"bytes,6,opt,name=lastName,proto3" json:"lastName,omitempty"`
	OrganisationName     string      `protobuf:"bytes,7,opt,name=organisationName,proto3" json:"organisationName,omitempty"`
	ContactEmail         string      `protobuf:"bytes,8,opt,name=contactEmail,proto3" json:"contactEmail,omitempty"`
	ContactMobile        string      `protobuf:"bytes,9,opt,name=contactMobile,proto3" json:"contactMobile,omitempty"`
	ContactPhone         string      `protobuf:"bytes,10,opt,name=contactPhone,proto3" json:"contactPhone,omitempty"`
	AddressStreet        string      `protobuf:"bytes,11,opt,name=addressStreet,proto3" json:"addressStreet,omitempty"`
	AddressCity          string      `protobuf:"bytes,12,opt,name=addressCity,proto3" json:"addressCity,omitempty"`
	AddressPostCode      string      `protobuf:"bytes,13,opt,name=addressPostCode,proto3" json:"addressPostCode,omitempty"`
	AddressState         string      `protobuf:"bytes,14,opt,name=addressState,proto3" json:"addressState,omitempty"`
	AddressCountry       string      `protobuf:"bytes,15,opt,name=addressCountry,proto3" json:"addressCountry,omitempty"`
	BalanceAmount        string      `protobuf:"bytes,16,opt,name=balanceAmount,proto3" json:"balanceAmount,omitempty"`
	EmployeeDetails      []*Employee `protobuf:"bytes,17,rep,name=employeeDetails,proto3" json:"employeeDetails,omitempty"`
	CreatedBy            string      `protobuf:"bytes,18,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	CreatedDate          string      `protobuf:"bytes,19,opt,name=createdDate,proto3" json:"createdDate,omitempty"`
	LastModifiedBy       string      `protobuf:"bytes,20,opt,name=lastModifiedBy,proto3" json:"lastModifiedBy,omitempty"`
	LastModifiedDate     string      `protobuf:"bytes,21,opt,name=lastModifiedDate,proto3" json:"lastModifiedDate,omitempty"`
	RecordState          string      `protobuf:"bytes,22,opt,name=recordState,proto3" json:"recordState,omitempty"`
	ReferencedBy         int64       `protobuf:"varint,23,opt,name=referencedBy,proto3" json:"referencedBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DataResponse_Data) Reset()         { *m = DataResponse_Data{} }
func (m *DataResponse_Data) String() string { return proto.CompactTextString(m) }
func (*DataResponse_Data) ProtoMessage()    {}
func (*DataResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdfd9498686a1cf0, []int{8, 0}
}

func (m *DataResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataResponse_Data.Unmarshal(m, b)
}
func (m *DataResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataResponse_Data.Marshal(b, m, deterministic)
}
func (m *DataResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataResponse_Data.Merge(m, src)
}
func (m *DataResponse_Data) XXX_Size() int {
	return xxx_messageInfo_DataResponse_Data.Size(m)
}
func (m *DataResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_DataResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_DataResponse_Data proto.InternalMessageInfo

func (m *DataResponse_Data) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DataResponse_Data) GetCustomerType() string {
	if m != nil {
		return m.CustomerType
	}
	return ""
}

func (m *DataResponse_Data) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *DataResponse_Data) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *DataResponse_Data) GetMiddleName() string {
	if m != nil {
		return m.MiddleName
	}
	return ""
}

func (m *DataResponse_Data) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *DataResponse_Data) GetOrganisationName() string {
	if m != nil {
		return m.OrganisationName
	}
	return ""
}

func (m *DataResponse_Data) GetContactEmail() string {
	if m != nil {
		return m.ContactEmail
	}
	return ""
}

func (m *DataResponse_Data) GetContactMobile() string {
	if m != nil {
		return m.ContactMobile
	}
	return ""
}

func (m *DataResponse_Data) GetContactPhone() string {
	if m != nil {
		return m.ContactPhone
	}
	return ""
}

func (m *DataResponse_Data) GetAddressStreet() string {
	if m != nil {
		return m.AddressStreet
	}
	return ""
}

func (m *DataResponse_Data) GetAddressCity() string {
	if m != nil {
		return m.AddressCity
	}
	return ""
}

func (m *DataResponse_Data) GetAddressPostCode() string {
	if m != nil {
		return m.AddressPostCode
	}
	return ""
}

func (m *DataResponse_Data) GetAddressState() string {
	if m != nil {
		return m.AddressState
	}
	return ""
}

func (m *DataResponse_Data) GetAddressCountry() string {
	if m != nil {
		return m.AddressCountry
	}
	return ""
}

func (m *DataResponse_Data) GetBalanceAmount() string {
	if m != nil {
		return m.BalanceAmount
	}
	return ""
}

func (m *DataResponse_Data) GetEmployeeDetails() []*Employee {
	if m != nil {
		return m.EmployeeDetails
	}
	return nil
}

func (m *DataResponse_Data) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *DataResponse_Data) GetCreatedDate() string {
	if m != nil {
		return m.CreatedDate
	}
	return ""
}

func (m *DataResponse_Data) GetLastModifiedBy() string {
	if m != nil {
		return m.LastModifiedBy
	}
	return ""
}

func (m *DataResponse_Data) GetLastModifiedDate() string {
	if m != nil {
		return m.LastModifiedDate
	}
	return ""
}

func (m *DataResponse_Data) GetRecordState() string {
	if m != nil {
		return m.RecordState
	}
	return ""
}

func (m *DataResponse_Data) GetReferencedBy() int64 {
	if m != nil {
		return m.ReferencedBy
	}
	return 0
}

type RawResponse struct {
	StatusCode           int32             `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message              string            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *RawResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RawResponse) Reset()         { *m = RawResponse{} }
func (m *RawResponse) String() string { return proto.CompactTextString(m) }
func (*RawResponse) ProtoMessage()    {}
func (*RawResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdfd9498686a1cf0, []int{9}
}

func (m *RawResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawResponse.Unmarshal(m, b)
}
func (m *RawResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawResponse.Marshal(b, m, deterministic)
}
func (m *RawResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawResponse.Merge(m, src)
}
func (m *RawResponse) XXX_Size() int {
	return xxx_messageInfo_RawResponse.Size(m)
}
func (m *RawResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RawResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RawResponse proto.InternalMessageInfo

func (m *RawResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *RawResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RawResponse) GetData() *RawResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type RawResponse_Data struct {
	CustomerType         []string `protobuf:"bytes,1,rep,name=customerType,proto3" json:"customerType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawResponse_Data) Reset()         { *m = RawResponse_Data{} }
func (m *RawResponse_Data) String() string { return proto.CompactTextString(m) }
func (*RawResponse_Data) ProtoMessage()    {}
func (*RawResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdfd9498686a1cf0, []int{9, 0}
}

func (m *RawResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawResponse_Data.Unmarshal(m, b)
}
func (m *RawResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawResponse_Data.Marshal(b, m, deterministic)
}
func (m *RawResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawResponse_Data.Merge(m, src)
}
func (m *RawResponse_Data) XXX_Size() int {
	return xxx_messageInfo_RawResponse_Data.Size(m)
}
func (m *RawResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_RawResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_RawResponse_Data proto.InternalMessageInfo

func (m *RawResponse_Data) GetCustomerType() []string {
	if m != nil {
		return m.CustomerType
	}
	return nil
}

type BalanceRequest struct {
	Header               *RequestHeader       `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Id                   int32                `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Data                 *BalanceRequest_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BalanceRequest) Reset()         { *m = BalanceRequest{} }
func (m *BalanceRequest) String() string { return proto.CompactTextString(m) }
func (*BalanceRequest) ProtoMessage()    {}
func (*BalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdfd9498686a1cf0, []int{10}
}

func (m *BalanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceRequest.Unmarshal(m, b)
}
func (m *BalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceRequest.Marshal(b, m, deterministic)
}
func (m *BalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceRequest.Merge(m, src)
}
func (m *BalanceRequest) XXX_Size() int {
	return xxx_messageInfo_BalanceRequest.Size(m)
}
func (m *BalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceRequest proto.InternalMessageInfo

func (m *BalanceRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *BalanceRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BalanceRequest) GetData() *BalanceRequest_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type BalanceRequest_Data struct {
	Amount               float64  `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BalanceRequest_Data) Reset()         { *m = BalanceRequest_Data{} }
func (m *BalanceRequest_Data) String() string { return proto.CompactTextString(m) }
func (*BalanceRequest_Data) ProtoMessage()    {}
func (*BalanceRequest_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdfd9498686a1cf0, []int{10, 0}
}

func (m *BalanceRequest_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceRequest_Data.Unmarshal(m, b)
}
func (m *BalanceRequest_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceRequest_Data.Marshal(b, m, deterministic)
}
func (m *BalanceRequest_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceRequest_Data.Merge(m, src)
}
func (m *BalanceRequest_Data) XXX_Size() int {
	return xxx_messageInfo_BalanceRequest_Data.Size(m)
}
func (m *BalanceRequest_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceRequest_Data.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceRequest_Data proto.InternalMessageInfo

func (m *BalanceRequest_Data) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type BalanceResponse struct {
	StatusCode           int32                 `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message              string                `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *BalanceResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *BalanceResponse) Reset()         { *m = BalanceResponse{} }
func (m *BalanceResponse) String() string { return proto.CompactTextString(m) }
func (*BalanceResponse) ProtoMessage()    {}
func (*BalanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdfd9498686a1cf0, []int{11}
}

func (m *BalanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceResponse.Unmarshal(m, b)
}
func (m *BalanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceResponse.Marshal(b, m, deterministic)
}
func (m *BalanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceResponse.Merge(m, src)
}
func (m *BalanceResponse) XXX_Size() int {
	return xxx_messageInfo_BalanceResponse.Size(m)
}
func (m *BalanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceResponse proto.InternalMessageInfo

func (m *BalanceResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *BalanceResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *BalanceResponse) GetData() *BalanceResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type BalanceResponse_Data struct {
	Amount               float64  `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BalanceResponse_Data) Reset()         { *m = BalanceResponse_Data{} }
func (m *BalanceResponse_Data) String() string { return proto.CompactTextString(m) }
func (*BalanceResponse_Data) ProtoMessage()    {}
func (*BalanceResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdfd9498686a1cf0, []int{11, 0}
}

func (m *BalanceResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceResponse_Data.Unmarshal(m, b)
}
func (m *BalanceResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceResponse_Data.Marshal(b, m, deterministic)
}
func (m *BalanceResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceResponse_Data.Merge(m, src)
}
func (m *BalanceResponse_Data) XXX_Size() int {
	return xxx_messageInfo_BalanceResponse_Data.Size(m)
}
func (m *BalanceResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceResponse_Data proto.InternalMessageInfo

func (m *BalanceResponse_Data) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func init() {
	proto.RegisterType((*RequestHeader)(nil), "sxcustomer.RequestHeader")
	proto.RegisterType((*Employee)(nil), "sxcustomer.Employee")
	proto.RegisterType((*RequestField)(nil), "sxcustomer.RequestField")
	proto.RegisterType((*RawRequest)(nil), "sxcustomer.RawRequest")
	proto.RegisterType((*GetRequest)(nil), "sxcustomer.GetRequest")
	proto.RegisterType((*CreateRequest)(nil), "sxcustomer.CreateRequest")
	proto.RegisterType((*ActionRequest)(nil), "sxcustomer.ActionRequest")
	proto.RegisterType((*UpdateRequest)(nil), "sxcustomer.UpdateRequest")
	proto.RegisterType((*DataResponse)(nil), "sxcustomer.DataResponse")
	proto.RegisterType((*DataResponse_Data)(nil), "sxcustomer.DataResponse.Data")
	proto.RegisterType((*RawResponse)(nil), "sxcustomer.RawResponse")
	proto.RegisterType((*RawResponse_Data)(nil), "sxcustomer.RawResponse.Data")
	proto.RegisterType((*BalanceRequest)(nil), "sxcustomer.BalanceRequest")
	proto.RegisterType((*BalanceRequest_Data)(nil), "sxcustomer.BalanceRequest.Data")
	proto.RegisterType((*BalanceResponse)(nil), "sxcustomer.BalanceResponse")
	proto.RegisterType((*BalanceResponse_Data)(nil), "sxcustomer.BalanceResponse.Data")
}

func init() { proto.RegisterFile("sxcustomer.proto", fileDescriptor_bdfd9498686a1cf0) }

var fileDescriptor_bdfd9498686a1cf0 = []byte{
	// 905 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0xcd, 0x92, 0xdb, 0x44,
	0x10, 0x2e, 0xad, 0x6c, 0xad, 0xb7, 0x6d, 0xd9, 0xcb, 0xb0, 0x6c, 0x06, 0x13, 0x82, 0x4b, 0x15,
	0xa8, 0xad, 0x1c, 0xb6, 0xc8, 0x86, 0x82, 0x53, 0xa0, 0x36, 0xbb, 0x21, 0xb9, 0x04, 0x52, 0x02,
	0x1e, 0x60, 0x56, 0x6a, 0x27, 0x02, 0x59, 0x63, 0x34, 0xe3, 0x4a, 0x7c, 0xcd, 0x9b, 0x70, 0xa0,
	0x8a, 0x87, 0xe0, 0x44, 0xf1, 0x3c, 0x3c, 0x03, 0x35, 0x3f, 0xb6, 0x35, 0xb2, 0x57, 0x88, 0x6c,
	0x6e, 0xee, 0x6f, 0x7a, 0xba, 0xa7, 0xbf, 0xe9, 0xfe, 0x46, 0x86, 0x43, 0xf1, 0x3a, 0x59, 0x08,
	0xc9, 0x67, 0x58, 0x9e, 0xce, 0x4b, 0x2e, 0x39, 0x81, 0x0d, 0x12, 0x7d, 0x0a, 0x61, 0x8c, 0xbf,
	0x2e, 0x50, 0xc8, 0xa7, 0xc8, 0x52, 0x2c, 0xc9, 0x11, 0x74, 0x25, 0xff, 0x05, 0x0b, 0xea, 0x4d,
	0xbc, 0x93, 0x83, 0xd8, 0x18, 0xd1, 0x3f, 0x1e, 0xf4, 0x1e, 0xcf, 0xe6, 0x39, 0x5f, 0x22, 0x92,
	0xdb, 0x70, 0x30, 0xcd, 0x4a, 0x21, 0xbf, 0x63, 0x33, 0xb4, 0x6e, 0x1b, 0x80, 0xdc, 0x01, 0x98,
	0x65, 0x69, 0x9a, 0xa3, 0x5e, 0xde, 0xd3, 0xcb, 0x15, 0x84, 0x8c, 0xa1, 0x97, 0x33, 0xbb, 0xd9,
	0xd7, 0xab, 0x6b, 0x5b, 0xad, 0xcd, 0xb9, 0xc8, 0x64, 0xc6, 0x0b, 0xda, 0x31, 0x6b, 0x2b, 0x9b,
	0x44, 0x30, 0x48, 0x78, 0x21, 0x59, 0x22, 0x9f, 0xbf, 0xe4, 0x05, 0xd2, 0xae, 0x5e, 0x77, 0x30,
	0x72, 0x17, 0x42, 0x6b, 0x3f, 0xe3, 0x57, 0x59, 0x8e, 0x34, 0xd0, 0x4e, 0x2e, 0x58, 0x89, 0xf4,
	0x78, 0xc6, 0xb2, 0x9c, 0xee, 0x3b, 0x91, 0x34, 0x16, 0xfd, 0xd9, 0x81, 0x81, 0x25, 0xe6, 0xdb,
	0x0c, 0xf3, 0x54, 0x6f, 0xb2, 0xa4, 0xfd, 0xb8, 0x9c, 0xaf, 0xea, 0x76, 0x30, 0x72, 0x0c, 0xc1,
	0xbc, 0xc4, 0x69, 0xf6, 0xda, 0x96, 0x6d, 0x2d, 0x97, 0x30, 0xbf, 0x99, 0xb0, 0x4e, 0x23, 0x61,
	0xdd, 0x1a, 0x61, 0xf7, 0xe0, 0x90, 0x97, 0x2f, 0x58, 0x91, 0x09, 0xa6, 0x48, 0xd2, 0x3e, 0xa6,
	0xe6, 0x2d, 0xbc, 0x4d, 0xd9, 0xdb, 0x04, 0xf6, 0x9a, 0x09, 0x34, 0x57, 0x71, 0xb0, 0xfb, 0x2a,
	0x58, 0x9a, 0x96, 0x28, 0xc4, 0x0f, 0xb2, 0x44, 0x94, 0x14, 0x4c, 0x24, 0x07, 0x24, 0x13, 0xe8,
	0x5b, 0xe0, 0x22, 0x93, 0x4b, 0xda, 0xd7, 0x3e, 0x55, 0x88, 0x9c, 0xc0, 0xc8, 0x9a, 0xcf, 0xb9,
	0x90, 0x17, 0x3c, 0x45, 0x3a, 0xd0, 0x5e, 0x75, 0x58, 0x9d, 0x6a, 0x1d, 0x9c, 0x49, 0xa4, 0xa1,
	0x39, 0x55, 0x15, 0x23, 0x9f, 0xc1, 0x70, 0x15, 0x9c, 0x2f, 0x0a, 0x59, 0x2e, 0xe9, 0x50, 0x7b,
	0xd5, 0x50, 0xf2, 0x35, 0x8c, 0xd0, 0xb6, 0xfb, 0x25, 0x4a, 0x96, 0xe5, 0x82, 0x8e, 0x26, 0xfe,
	0x49, 0xff, 0xec, 0xe8, 0xb4, 0x32, 0x4e, 0xab, 0x89, 0x88, 0xeb, 0xce, 0xd1, 0x37, 0x00, 0x31,
	0x7b, 0x65, 0x1b, 0x88, 0xdc, 0x87, 0xe0, 0xa5, 0x9e, 0x2e, 0xdd, 0x35, 0xfd, 0xb3, 0x0f, 0xab,
	0x41, 0x9c, 0xf1, 0x8b, 0xad, 0x63, 0xf4, 0x3d, 0xc0, 0x13, 0x94, 0x6f, 0x1f, 0x80, 0x0c, 0x61,
	0x2f, 0x4b, 0x75, 0x1f, 0x76, 0xe3, 0xbd, 0x2c, 0x8d, 0x4a, 0x08, 0x2f, 0x4a, 0x64, 0x12, 0x6f,
	0x10, 0xf3, 0x14, 0xba, 0x53, 0x35, 0x0c, 0x3a, 0x6c, 0xff, 0x8c, 0xee, 0xd8, 0xa1, 0x87, 0x25,
	0x36, 0x6e, 0xd1, 0x14, 0xc2, 0xf3, 0x44, 0xf5, 0xdf, 0xbb, 0xab, 0x83, 0x10, 0xe8, 0x14, 0x9b,
	0x31, 0xd2, 0xbf, 0xa3, 0x37, 0x1e, 0x84, 0x3f, 0xcd, 0xd3, 0x9b, 0x15, 0x57, 0x4f, 0xb4, 0x2e,
	0xd6, 0x6f, 0x57, 0xec, 0x5f, 0xfb, 0x30, 0xb8, 0x64, 0x92, 0xc5, 0x28, 0xe6, 0xbc, 0x10, 0x7a,
	0xae, 0x85, 0x64, 0x72, 0x21, 0x74, 0xd3, 0x7a, 0x3a, 0x70, 0x05, 0x21, 0x14, 0xf6, 0x67, 0x28,
	0x04, 0x7b, 0xb1, 0x52, 0xc9, 0x95, 0x49, 0xee, 0x43, 0x27, 0x65, 0x92, 0xd9, 0xcc, 0x1f, 0x57,
	0x33, 0x57, 0x33, 0x18, 0x43, 0xbb, 0x8e, 0xff, 0x0e, 0xa0, 0xa3, 0x4c, 0x5b, 0x86, 0x51, 0x27,
	0x55, 0x46, 0x5d, 0xb7, 0xf6, 0x1a, 0x75, 0xcb, 0xbf, 0x5e, 0xb7, 0x3a, 0xcd, 0xba, 0xd5, 0x6d,
	0xd4, 0xad, 0xa0, 0x85, 0x6e, 0xed, 0xb7, 0xd4, 0xad, 0x5e, 0x1b, 0xdd, 0x3a, 0x68, 0xa3, 0x5b,
	0xd0, 0x46, 0xb7, 0xfa, 0x2d, 0x74, 0x6b, 0xd0, 0x4a, 0xb7, 0xc2, 0x76, 0xba, 0x35, 0x6c, 0xa5,
	0x5b, 0xa3, 0x9d, 0xba, 0x75, 0x17, 0xc2, 0x2b, 0x96, 0xb3, 0x22, 0xc1, 0xf3, 0x99, 0x82, 0xe8,
	0xa1, 0x39, 0xbd, 0x03, 0xee, 0x52, 0xb7, 0xf7, 0xfe, 0x87, 0xba, 0xa9, 0xbe, 0x48, 0xb4, 0x96,
	0xa4, 0x8f, 0x96, 0x94, 0x98, 0xbe, 0x58, 0x03, 0x8a, 0x1b, 0x6b, 0x5c, 0xaa, 0x72, 0xde, 0x37,
	0xdc, 0x54, 0x20, 0x55, 0x8d, 0xea, 0x84, 0x67, 0x3c, 0xcd, 0xa6, 0x99, 0x0e, 0x72, 0x64, 0xaa,
	0x71, 0x51, 0xd5, 0x25, 0x55, 0x44, 0x87, 0xfb, 0xc0, 0x74, 0x49, 0x1d, 0x57, 0x59, 0x4b, 0x4c,
	0x78, 0x99, 0x1a, 0x12, 0x8f, 0x4d, 0xd6, 0x0a, 0xa4, 0x78, 0x2e, 0x71, 0x8a, 0x25, 0x16, 0x89,
	0xce, 0x79, 0x6b, 0xe2, 0x9d, 0xf8, 0xb1, 0x83, 0x45, 0xbf, 0x7b, 0xd0, 0xd7, 0xc2, 0x7d, 0xe3,
	0x19, 0xfe, 0xdc, 0x99, 0xe1, 0xdb, 0x8e, 0x7a, 0x6c, 0x12, 0x54, 0x47, 0xf8, 0x9e, 0x9d, 0xe0,
	0xed, 0x2f, 0x0d, 0xbf, 0x3e, 0xb1, 0xd1, 0x1f, 0x1e, 0x0c, 0x1f, 0x99, 0x3b, 0x7d, 0x87, 0x92,
	0xf7, 0xc0, 0x39, 0xf3, 0x27, 0xd5, 0x00, 0x6e, 0xb2, 0xea, 0xb1, 0xef, 0xd8, 0x63, 0x1f, 0x43,
	0xc0, 0x4c, 0xcf, 0xa9, 0xfc, 0x5e, 0x6c, 0xad, 0xe8, 0x37, 0x0f, 0x46, 0xeb, 0xdd, 0x37, 0xa6,
	0xf5, 0x0b, 0xe7, 0x88, 0x93, 0x9d, 0x47, 0xdc, 0xa6, 0xf6, 0x3f, 0xce, 0x78, 0xf6, 0xc6, 0x87,
	0xde, 0x85, 0x8d, 0x43, 0xbe, 0x04, 0x3f, 0x66, 0xaf, 0xc8, 0xf1, 0xd6, 0x95, 0xe9, 0xd2, 0xc7,
	0xb7, 0xae, 0xb9, 0x4a, 0xf2, 0x10, 0x02, 0xf3, 0xc2, 0x12, 0x87, 0x7a, 0xe7, 0xd5, 0x1d, 0xd3,
	0xeb, 0xc4, 0x9c, 0x7c, 0x05, 0xfe, 0x13, 0x94, 0x6e, 0xda, 0xcd, 0x27, 0x40, 0xc3, 0xc6, 0x87,
	0x10, 0x98, 0x57, 0xd6, 0xcd, 0xeb, 0xbc, 0xbc, 0xcd, 0xdb, 0xcd, 0xdb, 0xe9, 0x6e, 0x77, 0xde,
	0xd3, 0x86, 0xed, 0x4f, 0x21, 0x3c, 0x4f, 0x7f, 0x5e, 0x08, 0x69, 0xe9, 0x27, 0xe3, 0xeb, 0xdb,
	0x66, 0xfc, 0x51, 0xc3, 0x7d, 0x5d, 0x05, 0xfa, 0xdf, 0xc9, 0x83, 0x7f, 0x03, 0x00, 0x00, 0xff,
	0xff, 0xce, 0xfc, 0x91, 0xd2, 0xb1, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CustomerClient is the client API for Customer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CustomerClient interface {
	Raw(ctx context.Context, in *RawRequest, opts ...grpc.CallOption) (*RawResponse, error)
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*DataResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*DataResponse, error)
	Action(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*DataResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*DataResponse, error)
	AdjustBalance(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*BalanceResponse, error)
}

type customerClient struct {
	cc *grpc.ClientConn
}

func NewCustomerClient(cc *grpc.ClientConn) CustomerClient {
	return &customerClient{cc}
}

func (c *customerClient) Raw(ctx context.Context, in *RawRequest, opts ...grpc.CallOption) (*RawResponse, error) {
	out := new(RawResponse)
	err := c.cc.Invoke(ctx, "/sxcustomer.Customer/Raw", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*DataResponse, error) {
	out := new(DataResponse)
	err := c.cc.Invoke(ctx, "/sxcustomer.Customer/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*DataResponse, error) {
	out := new(DataResponse)
	err := c.cc.Invoke(ctx, "/sxcustomer.Customer/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) Action(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*DataResponse, error) {
	out := new(DataResponse)
	err := c.cc.Invoke(ctx, "/sxcustomer.Customer/Action", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*DataResponse, error) {
	out := new(DataResponse)
	err := c.cc.Invoke(ctx, "/sxcustomer.Customer/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) AdjustBalance(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*BalanceResponse, error) {
	out := new(BalanceResponse)
	err := c.cc.Invoke(ctx, "/sxcustomer.Customer/AdjustBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomerServer is the server API for Customer service.
type CustomerServer interface {
	Raw(context.Context, *RawRequest) (*RawResponse, error)
	Create(context.Context, *CreateRequest) (*DataResponse, error)
	Get(context.Context, *GetRequest) (*DataResponse, error)
	Action(context.Context, *ActionRequest) (*DataResponse, error)
	Update(context.Context, *UpdateRequest) (*DataResponse, error)
	AdjustBalance(context.Context, *BalanceRequest) (*BalanceResponse, error)
}

// UnimplementedCustomerServer can be embedded to have forward compatible implementations.
type UnimplementedCustomerServer struct {
}

func (*UnimplementedCustomerServer) Raw(ctx context.Context, req *RawRequest) (*RawResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Raw not implemented")
}
func (*UnimplementedCustomerServer) Create(ctx context.Context, req *CreateRequest) (*DataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedCustomerServer) Get(ctx context.Context, req *GetRequest) (*DataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedCustomerServer) Action(ctx context.Context, req *ActionRequest) (*DataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Action not implemented")
}
func (*UnimplementedCustomerServer) Update(ctx context.Context, req *UpdateRequest) (*DataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedCustomerServer) AdjustBalance(ctx context.Context, req *BalanceRequest) (*BalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdjustBalance not implemented")
}

func RegisterCustomerServer(s *grpc.Server, srv CustomerServer) {
	s.RegisterService(&_Customer_serviceDesc, srv)
}

func _Customer_Raw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).Raw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sxcustomer.Customer/Raw",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).Raw(ctx, req.(*RawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customer_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sxcustomer.Customer/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customer_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sxcustomer.Customer/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customer_Action_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).Action(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sxcustomer.Customer/Action",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).Action(ctx, req.(*ActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customer_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sxcustomer.Customer/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customer_AdjustBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).AdjustBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sxcustomer.Customer/AdjustBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).AdjustBalance(ctx, req.(*BalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Customer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sxcustomer.Customer",
	HandlerType: (*CustomerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Raw",
			Handler:    _Customer_Raw_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Customer_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Customer_Get_Handler,
		},
		{
			MethodName: "Action",
			Handler:    _Customer_Action_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Customer_Update_Handler,
		},
		{
			MethodName: "AdjustBalance",
			Handler:    _Customer_AdjustBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sxcustomer.proto",
}
